### ISSUE TITLE
ORDER_STATUS_COMPLETE Send error

### ISSUE THREAD

**Issue by Oleh7777** [PayU-EMEA/woo-payu-payment-gateway#31]
W historii raportów taka chyba i nie zmienia status transakcji na stronie

ORDER_STATUS_COMPLETE | code (ERROR): 502, Response: "<html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> "
-- | --

**Comment by mateuszhublewski** [comment]
Udało Ci się rozwiązać problem?

**Comment by regdos** [comment]
@Oleh7777 proszę o kontakt z pomocą PayU żeby dokładnie przeanalizować problem

**Comment by Oleh7777** [comment]
> Udało Ci się rozwiązać problem? @Oleh7777

nie
czekam na support PayU
