### ISSUE TITLE
Brak metody płatności PayU/Blik w sklepie

### ISSUE THREAD

**Issue by rafalsitarz** [PayU-EMEA/woo-payu-payment-gateway#46]
Cześć,
mam temat tego typu: założyłem w PayU konto, otrzymałem ID punktu płatności, drugi klucz md5, OAuth - client_id, oraz client_secret. Zainstalowałem plugin Wtyczka Płacę z PayU dla Woocommerce i aktywowałem. Pola Sandbox mam obecnie puste.
W metodach płatności nie pojawia mi się opcja PayU/blik. Mam zaznaczone płatności WooCommerce - dostaję tradycyjny przelew lub platnosc karta na stronie. Blika brak. 
Pomożecie?

**Comment by adrianratajczak** [comment]
Cześć, czy w ustawieniach PayU masz włączonego blika? 
https://poland.payu.com/nasze-rozwiazania/blik/

**Comment by regdos** [comment]
Proszę o kontakt z BOK PayU bo wygląda to na jakiś problem konfiguracji albo braku bramki Blik.
