### ISSUE TITLE
Warning: require_once(includes/WC_PayUGateways.php): failed to open stream

### ISSUE THREAD

**Issue by sascompl** [PayU-EMEA/woo-payu-payment-gateway#57]
Warning: require_once(includes/WC_PayUGateways.php): failed to open stream: No such file or directory in /wp-content/plugins/woo-payu-payment-gateway/woocommerce-gateway-payu.php on line 36

Fatal error: require_once(): Failed opening required 'includes/WC_PayUGateways.php' (include_path='.:/:/usr/local/php74/lib/pear') in /wp-content/plugins/woo-payu-payment-gateway/woocommerce-gateway-payu.php on line 36
![Zrzut ekranu 2023-05-24 o 20 35 43](https://github.com/PayU-EMEA/woo-payu-payment-gateway/assets/134546670/4d2d43b9-7f43-42de-9574-8b23936f8da3)
![Zrzut ekranu 2023-05-24 o 20 33 28](https://github.com/PayU-EMEA/woo-payu-payment-gateway/assets/134546670/c7b62fe0-3bbc-46c7-8757-af58553a50fb)
 
https://melyo.pl/

**Comment by sascompl** [comment]
![Zrzut ekranu 2023-05-24 o 20 33 14](https://github.com/PayU-EMEA/woo-payu-payment-gateway/assets/134546670/29b8014e-f8f0-4f24-a76c-c04ad34ab569)

**Comment by regdos** [comment]
Niestety nie jesteśmy w stanie powtórzyć tego błędu. Nazwy plików, katalog, itp. wyglądają prawidłowo.
