### ISSUE TITLE
Brak kompatybilności z ostatnią wersją WooCommerce

### ISSUE THREAD

**Issue by evolucja** [PayU-EMEA/woo-payu-payment-gateway#62]
Cześć,
WooCommerce w najnowszej wersji z 16 listopada domyślnie ustawia strony zamówienia w wersji blokowej:
https://woo.com/document/cart-checkout-blocks-status/

![image](https://github.com/PayU-EMEA/woo-payu-payment-gateway/assets/990929/6d627e3a-f203-4a96-947b-1b1a152dbe3e)

Wasza wtyczka nie jest z nim kompatybilna. Oczywiście można przełączyć się na Classic, ale nie o to chodzi, a rynek przestawia się na te bloki i wszystkie pozostałe wtyczki, z których korzystamy są już dostosowane.

Czy jest szansa na szybką aktualizację?

**Comment by regdos** [comment]
Jest planowana taka aktualizacja, natomiast na ten moment nie znany jest termin.

**Comment by regdos** [comment]
Od wersji 2.2.0 wprowadziliśmy obsługę bloków. Na razie dla dwóch metod, ale będziemy sukcesywnie wprowadzać kolejne metody.

**Comment by swieza-strona** [comment]
Hej, proszę o podanie listy metod które wspierane są przez checkout blokowy na dzień dzisiejszy. Pozdrawiam i z góry dziękuję za pomoc :)

**Comment by regdos** [comment]
Zgodnie z informacją w tabelce na https://github.com/PayU-EMEA/woo-payu-payment-gateway aktualnie wspieramy wszystkie metody, które udostępnia nasza wtyczka.
