### ISSUE TITLE
After successful payment, status does not update

### ISSUE THREAD

**Issue by Vastuney** [PayU-EMEA/woo-payu-payment-gateway#64]
Hi,

I have been using the plugin for a long time and never had a problem, somehow 2-3 days ago there was a problem that the order statuses do not update after a successful payment. Nothing has been changed for a long time.

**Comment by mbaraneq** [comment]
Same problem here, but in sandbox. Status not updating after choosing payment approved in sandbox.

**Comment by regdos** [comment]
It is a problem with WAF on server. Probably blocks PayU IP (185.68.12.0/24, 185.68.14.0/24).  Please contact with hosting company.
