### ISSUE TITLE
Żadna metoda płatności nie jest dostępna

### ISSUE THREAD

**Issue by juadax** [PayU-EMEA/woo-payu-payment-gateway#72]
Konto PayU zostało aktywowane. Wtyczka skonfigurowana zgodnie z instrukcją. W ustawieniach WooCommerce włączone zostały metody płatności PayU - karta kredytowa, PayU - lista banków, PayU - Blik. Niestety w sklepie cały czas widnieje komunikat "Żadna metoda płatności nie jest dostępna. Być może problem jest po naszej stronie. Skontaktuj się z nami, jeśli potrzebujesz pomocy przy złożeniu zamówienia." Jaka może być przyczyna, że nie pojawiają się metody płatności?

Z góry dziękuję za pomoc.

<img width="907" alt="image" src="https://github.com/PayU-EMEA/woo-payu-payment-gateway/assets/170333490/15f1dd60-bddf-4245-92a8-bcf585c329ff">

**Comment by dareksf** [comment]
Mam taki sam problem, czy jest jakieś rozwiązanie tego problemu?

**Comment by juadax** [comment]
Niestety brak odpowiedzi z supportu i jakiejkolwiek pomocy na infolinii. Udało nam się  po czasie znaleźć, że należy przełączyć WooCommerce na stary checkout

 
<img width="294" alt="Zrzut ekranu 2024-06-6 o 11 51 37" src="https://github.com/PayU-EMEA/woo-payu-payment-gateway/assets/170333490/89ac0eb2-708b-4dae-8ac1-dbc52459267d">

**Comment by regdos** [comment]
W sekcji "znane problemy" była informacja, że plugin nie obsługuje bloków w procesie zakupowym. Od wersji 2.2.0 wprowadziliśmy obsługę bloków. Na razie dla dwóch metod, ale będziemy sukcesywnie wprowadzać kolejne metody.
