### ISSUE TITLE
Przy płatności online poprawnej nie ma powiadomienia email dla administratora o nowym zamówieniu

### ISSUE THREAD

**Issue by sinteit** [PayU-EMEA/woo-payu-payment-gateway#73]
Witam,

Po wdrożeniu płatności PayU dla zamówień tak opłaconych z poprawnym statusem płatności nie ma powiadomienia e-mail o złożonym zamówieniu które powinno przyjść do admina lub na adresy skonfigurowane w sekcji email woocommerce. Powiadomienia przychodzą dla zamówień bez płatności online payu, zatem wysyłka maili ogólnie działa.
Testowałem to na standardowej konfiguracji powiadomień jak i przy wysyłce SMTP wtyczką WP Mail.

Jaka może być tego przyczyna?

**Comment by regdos** [comment]
Szczegółową analizę problemu otrzyma Pan od wsparcia PayU. Wkrótce przygotujemy poprawkę.

**Comment by sinteit** [comment]
Czy mam rozumieć, że problem został zauważony i będzie w tym kierunku przygotowana aktualizacja z fixem tego zagadnienia?

**Comment by regdos** [comment]
Tak.
