### ISSUE TITLE
Wersja Wersja 2.2.1 - generuje w panelu WP wiele ostrzeżeń

### ISSUE THREAD

**Issue by dgdb1** [PayU-EMEA/woo-payu-payment-gateway#75]
Po aktualizacji do najnowsze wersji jest seria błędów w panelu WP. Jak to naprawić? Pomaga tylko dezaktywacja wtyczki. 

`Warning: Attempt to read property "total" on null in /home/klient.dhosting.pl/XXX/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 271

Warning: Cannot modify header information - headers already sent by (output started at /home/klient.dhosting.pl/XXX/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php:271) in /home/klient.dhosting.pl/XXX/public_html/wp-includes/functions.php on line 7096

Warning: Cannot modify header information - headers already sent by (output started at /home/klient.dhosting.pl/XXX/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php:271) in /home/klient.dhosting.pl/XXX/public_html/wp-admin/admin-header.php on line 9
```

**Comment by maciekzam** [comment]
Potwierdzam, u mnie również występuje ten błąd: Warning: Attempt to read property "total" on null in /home/klient.dhosting.pl/XXX/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 271

Po cofnięciu do wersji 2.1.0 znika

**Comment by regdos** [comment]
@dgdb1 @maciekzam Proszę podmieńcie na serwerze plik https://github.com/PayU-EMEA/woo-payu-payment-gateway/blob/master/Payu/Gateways/WC_Payu_Gateways.php
Jeżeli będzie wydamy nową wersje z tą poprawką.

**Comment by regdos** [comment]
Poprawione w wersji 2.2.2
