### ISSUE TITLE
PHP Fatal error on plugin activation

### ISSUE THREAD

**Issue by turvodnik** [PayU-EMEA/woo-payu-payment-gateway#79]
`PHP Fatal error: Uncaught Error: Failed opening required '[/var/www/vhosts/site.eu/httpdocs/wp-content/plugins/woo-payu-payment-gateway-master/vendor/autoload.php](https://217.160.000.00:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Fwoo-payu-payment-gateway-master%2Fvendor&subscriptionId=4&file=autoload.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)' (include_path='.:/opt/plesk/php/8.2/share/pear') in [/var/www/vhosts/site.eu/httpdocs/wp-content/plugins/woo-payu-payment-gateway-master/woocommerce-gateway-payu.php](https://217.160.000.00:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Fwoo-payu-payment-gateway-master&subscriptionId=4&file=woocommerce-gateway-payu.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4):39
Stack trace:
#0 [/var/www/vhosts/site.eu/httpdocs/wp-admin/includes/plugin.php](https://217.160.000.00:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-admin%2Fincludes&subscriptionId=4&file=plugin.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(2387): include_once()
#1 [/var/www/vhosts/site.eu/httpdocs/wp-admin/includes/plugin.php](https://217.160.000.00:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-admin%2Fincludes&subscriptionId=4&file=plugin.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(673): plugin_sandbox_scrape()
#2 [/var/www/vhosts/site.eu/httpdocs/wp-admin/plugins.php](https://217.160.000.00:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-admin&subscriptionId=4&file=plugins.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(60): activate_plugin()
#3 {main}
thrown in [/var/www/vhosts/site.eu/httpdocs/wp-content/plugins/woo-payu-payment-gateway-master/woocommerce-gateway-payu.php](https://217.160.000.00:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Fwoo-payu-payment-gateway-master&subscriptionId=4&file=woocommerce-gateway-payu.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4) on line 39`

**Comment by regdos** [comment]
Please install the plugin according to the instructions. The source code downloaded from the repo is not a finished plugin.
